defaults: &defaults
  adapter: mysql2
  username: root
  password:
  encoding: utf8
  host: 127.0.0.1

development:
  <<: *defaults
  database: memo_station_development

test:
  <<: *defaults
  database: memo_station_test

production:
  <<: *defaults
  database: memo_station_production
